version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=volunteers-pg
      - DB_PORT=5432
      - DB_NAME=postgres
      - APP_PORT=80

  postgres:
    image: 'postgres:15.0'
    container_name: volunteers-pg
    ports:
      - "5555:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_DB=volunteers-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
